### ISSUE TITLE
macOs windowed app tracing does not properly show Chrome apps & Electron apps

### ISSUE THREAD

**Issue by BobEvans** [google/taqo-paco#148]
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by rundong08** [comment]
A few things to note:

For a macOS application process, the `title` property is "the title of the UI element as it appears on the screen", e.g. "Google Chat" or "Chrome Remote Desktop", while the `name` property could be something else such as "app_mode_loader" or "Electron".

For applescript, assigning object to a variable only stores an object specifier, but not the object itself or even a pointer to the object. For example, the frontmost app could be `application process "app_mode_loader" of "System Events"`, but that object specifier always resolve to the same object, even when both "Google Chat" or "Chrome Remote Desktop" were opened. This will cause "Google Chat" being resolved as "Chrome Remote Desktop" or vice versa, depending on which one is first opened. The solution is to always refer to an process by its `id` instead of name.
